# =======================================================
# SonarQube Project Configuration — pianolouvorja/web
# =======================================================
sonar.projectKey=pianolouvorja:web
sonar.projectName=Piano Louvor JA Web

sonar.sources=src
sonar.host.url=http://127.0.0.1:9000

sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts

sonar.typescript.tsconfigPath=tsconfig.json
