blank_issues_enabled: false
contact_links:
  - name: 💬 Discord da comunidade
    url: https://discord.gg/louvorja
    about: Para dúvidas e discussões gerais
  - name: 📧 Contato direto
    url: mailto:app@pianolouvorja.com.br
    about: Para assuntos privados
